In [1]:
import pandas as pd

df = pd.read_csv("../../data/Sales.csv", parse_dates=True, index_col=0)
df.head()

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [2]:
df.shape

(113036, 17)

In [3]:
df.columns

Index(['Day', 'Month', 'Year', 'Customer_Age', 'Age_Group', 'Customer_Gender',
       'Country', 'State', 'Product_Category', 'Sub_Category', 'Product',
       'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Profit', 'Cost',
       'Revenue'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 113036 entries, 2013-11-26 to 2016-03-04
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Day               113036 non-null  int64
 1   Month             113036 non-null  object
 2   Year              113036 non-null  int64
 3   Customer_Age      113036 non-null  int64
 4   Age_Group         113036 non-null  object
 5   Customer_Gender   113036 non-null  object
 6   Country           113036 non-null  object
 7   State             113036 non-null  object
 8   Product_Category  113036 non-null  object
 9   Sub_Category      113036 non-null  object
 10  Product           113036 non-null  object
 11  Order_Quantity    113036 non-null  int64
 12  Unit_Cost         113036 non-null  int64
 13  Unit_Price        113036 non-null  int64
 14  Profit            113036 non-null  int64
 15  Cost              113036 non-null  int64
 16  Revenue           113036 non-null  int64
dtypes: int64(9), object(8)
memory usage: 15.5+ MB

In [5]:
df.index

DatetimeIndex(['2013-11-26', '2015-11-26', '2014-03-23', '2016-03-23',
               '2014-05-15', '2016-05-15', '2014-05-22', '2016-05-22',
               '2014-02-22', '2016-02-22',
               ...
               '2013-07-08', '2015-07-08', '2013-12-28', '2015-12-28',
               '2014-04-12', '2016-04-12', '2014-04-02', '2016-04-02',
               '2014-03-04', '2016-03-04'],
              dtype='datetime64[ns]', name='Date', length=113036, freq=None)

In [6]:
df = df.sort_index()
df.head()

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2011-01-01,1,January,2011,42,Adults (35-64),M,United States,California,Bikes,Road Bikes,"Road-750 Black, 44",1,344,540,185,344,529
2011-01-01,1,January,2011,33,Young Adults (25-34),F,France,Yveline,Bikes,Road Bikes,"Road-150 Red, 48",2,2171,3578,1097,4342,5439
2011-01-01,1,January,2011,17,Youth (<25),M,Canada,British Columbia,Bikes,Road Bikes,"Road-250 Red, 44",1,1519,2443,900,1519,2419
2011-01-01,1,January,2011,39,Adults (35-64),M,United States,Washington,Bikes,Road Bikes,"Road-550-W Yellow, 38",3,713,1120,482,2139,2621
2011-01-01,1,January,2011,23,Youth (<25),M,Australia,Victoria,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252,2295,561,1252,1813

In [8]:
df.loc["2014-01-20": "2014-01-25"]

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2014-01-20,20,January,2014,23,Youth (<25),M,United States,Washington,Bikes,Road Bikes,"Road-750 Black, 52",1,344,540,77,344,421
2014-01-20,20,January,2014,50,Adults (35-64),M,Canada,British Columbia,Clothing,Caps,AWC Logo Cap,19,7,9,36,133,169
2014-01-20,20,January,2014,51,Adults (35-64),M,United States,Washington,Accessories,Bottles and Cages,Water Bottle - 30 oz.,16,2,5,30,32,62
2014-01-20,20,January,2014,46,Adults (35-64),F,United States,California,Accessories,Tires and Tubes,Mountain Tire Tube,21,2,5,61,42,103
2014-01-20,20,January,2014,46,Adults (35-64),F,United States,California,Accessories,Tires and Tubes,Mountain Tire Tube,13,2,5,38,26,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-01-25,25,January,2014,21,Youth (<25),F,Germany,Nordrhein-Westfalen,Accessories,Hydration Packs,Hydration Pack - 70 oz.,21,21,55,564,441,1005
2014-01-25,25,January,2014,32,Young Adults (25-34),M,United Kingdom,England,Accessories,Tires and Tubes,Touring Tire Tube,23,2,5,64,46,110
2014-01-25,25,January,2014,41,Adults (35-64),M,United States,Washington,Clothing,Jerseys,"Long-Sleeve Logo Jersey, S",1,38,50,1,38,39
2014-01-25,25,January,2014,37,Adults (35-64),F,Australia,New South Wales,Clothing,Jerseys,"Long-Sleeve Logo Jersey, M",16,38,50,88,608,696
2014-01-25,25,January,2014,26,Young Adults (25-34),F,United Kingdom,England,Accessories,Tires and Tubes,Touring Tire Tube,30,2,5,84,60,144

In [9]:
df["State"].value_counts()

State
California             22450
British Columbia       14116
England                13620
Washington             11264
New South Wales        10412
Victoria                6016
Oregon                  5286
Queensland              5220
Saarland                2770
Nordrhein-Westfalen     2484
Hessen                  2384
Seine (Paris)           2328
Hamburg                 1836
Seine Saint Denis       1684
Nord                    1670
South Australia         1564
Bayern                  1426
Hauts de Seine          1084
Essonne                  994
Yveline                  954
Tasmania                 724
Seine et Marne           394
Moselle                  386
Loiret                   382
Val d'Oise               264
Garonne (Haute)          208
Brandenburg              198
Val de Marne             158
Charente-Maritime        148
Somme                    134
Loir et Cher             120
Pas de Calais             90
Alberta                   56
Texas                     30
Ohio                      28
Illinois                  28
New York                  20
Florida                   14
Kentucky                  10
South Carolina            10
Utah                      10
Georgia                    8
Wyoming                    8
Ontario                    6
Missouri                   6
Minnesota                  6
Montana                    6
Arizona                    4
North Carolina             4
Mississippi                4
Alabama                    4
Virginia                   4
Massachusetts              2
Name: count, dtype: int64

In [10]:
df["Product_Category"].unique()

array(['Bikes', 'Accessories', 'Clothing'], dtype=object)

In [ ]:
df.query("Product_Category == 'Accessories'").head()

,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Date,,,,,,,,,,,,,,,,,
2013-07-01,1,July,2013,41,Adults (35-64),M,Germany,Hessen,Accessories,Bottles and Cages,Road Bottle Cage,28,3,9,150,84,234
2013-07-01,1,July,2013,41,Adults (35-64),M,Germany,Hessen,Accessories,Bottles and Cages,Road Bottle Cage,5,3,9,27,15,42
2013-07-01,1,July,2013,42,Adults (35-64),F,France,Seine Saint Denis,Accessories,Helmets,"Sport-100 Helmet, Blue",2,13,35,31,26,57
2013-07-01,1,July,2013,28,Young Adults (25-34),F,Australia,New South Wales,Accessories,Bottles and Cages,Water Bottle - 30 oz.,2,2,5,5,4,9
2013-07-01,1,July,2013,33,Young Adults (25-34),F,United States,Washington,Accessories,Tires and Tubes,Patch Kit/8 Patches,30,1,2,17,30,47

In [12]:
df["Country"].value_counts()

Country
United States     39206
Australia         23936
Canada            14178
United Kingdom    13620
Germany           11098
France            10998
Name: count, dtype: int64

In [13]:
type(df["Country"].value_counts())

pandas.core.series.Series

In [14]:
df["Country"].value_counts().to_json()

'{"United States":39206,"Australia":23936,"Canada":14178,"United Kingdom":13620,"Germany":11098,"France":10998}'

## Profit per country

In [15]:
import duckdb

duckdb.query("""
    SELECT country, SUM(profit) AS Profit
    FROM df
    GROUP BY country
    ORDER BY Profit DESC
""").df().to_json()

'{"Country":{"0":"United States","1":"Australia","2":"United Kingdom","3":"Canada","4":"Germany","5":"France"},"Profit":{"0":11073644.0,"1":6776030.0,"2":4413853.0,"3":3717296.0,"4":3359995.0,"5":2880282.0}}'